CREATE DATABASE BD_TESTE;

USE BD_TESTE;

CREATE TABLE IF NOT EXISTS CLIENTE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100),
	CIDADE VARCHAR(100),
	UF VARCHAR(2)
);
CREATE INDEX IF NOT EXISTS idx_CLIENTE_NOME ON CLIENTE(NOME);

CREATE TABLE IF NOT EXISTS PRODUTO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(100),
	PRECO DECIMAL(10,2)
);
CREATE INDEX IF NOT EXISTS idx_PRODUTO_DESCRICAO ON PRODUTO(DESCRICAO);

CREATE TABLE IF NOT EXISTS PEDIDO (
	NUMERO INT PRIMARY KEY,
	DATA_EMISSAO DATE,
	ID_CLIENTE INT,	
	VALOR_TOTAL DECIMAL(10,2),
    CONSTRAINT FK_IDCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
);
CREATE INDEX IF NOT EXISTS idx_PEDIDO_DATA_EMISSAO ON PEDIDO(DATA_EMISSAO);

CREATE TABLE IF NOT EXISTS PEDIDO_PRODUTO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NUMERO_PEDIDO INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE DECIMAL(10,0),
	PRECO DECIMAL(10,2),
	VALOR_TOTAL DECIMAL(10,2),
    CONSTRAINT FK_NUMEROPEDIDO FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDO (NUMERO),
    CONSTRAINT FK_IDPRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);

INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('João da Silva', 'São Paulo', 'SP');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Maria Oliveira', 'Rio de Janeiro', 'RJ');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Pedro Souza', 'Belo Horizonte', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Ana Pereira', 'Salvador', 'BA');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Luiz Santos', 'Fortaleza', 'CE');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Carla Costa', 'Recife', 'PE');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Rafael Almeida', 'Brasília', 'DF');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Fernanda Lima', 'Manaus', 'AM');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Marcos Oliveira', 'Curitiba', 'PR');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Julia Rodrigues', 'Porto Alegre', 'RS');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Diego Costa', 'Belém', 'PA');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Camila Martins', 'Goiânia', 'GO');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Lucas Ferreira', 'São Luís', 'MA');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Mariana Carvalho', 'Natal', 'RN');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Gustavo Silva', 'João Pessoa', 'PB');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Amanda Sousa', 'Maceió', 'AL');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Daniel Rodrigues', 'Campo Grande', 'MS');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Larissa Oliveira', 'Teresina', 'PI');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Felipe Alves', 'Florianópolis', 'SC');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Isabela Santos', 'Vitória', 'ES');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Thiago Lima', 'Cuiabá', 'MT');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Carolina Fernandes', 'Aracaju', 'SE');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Eduardo Pereira', 'Porto Velho', 'RO');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Natália Costa', 'Palmas', 'TO');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Alexandre Almeida', 'Boa Vista', 'RR');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Patrícia Oliveira', 'Rio Branco', 'AC');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Marcelo Rodrigues', 'Macapá', 'AP');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Vanessa Souza', 'Porto Seguro', 'BA');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Ricardo Martins', 'Campos dos Goytacazes', 'RJ');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Fernanda Pereira', 'Petrópolis', 'RJ');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Luciana Silva', 'Niterói', 'RJ');

INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Camiseta Branca', 39.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Calça Jeans', 89.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Vestido Floral', 129.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Camisa Xadrez', 49.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blusa de Tricô', 59.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Shorts Jeans', 69.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Jaqueta de Couro', 149.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Saia Plissada', 34.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Suéter de Cashmere', 119.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Calça Legging', 29.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Casaco de Inverno', 99.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blusa de Manga Longa', 39.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Bermuda Esportiva', 49.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Macacão Jeans', 89.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Camiseta Estampada', 44.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blazer Clássico', 74.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Vestido de Festa', 169.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Calça Social', 59.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Cardigã de Lã', 49.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Shorts Estampado', 64.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Jaqueta Corta-Vento', 79.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Saia Midi', 39.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Moletom Confortável', 54.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Legging Esportiva', 29.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Casaco Acolchoado', 109.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blusa de Malha', 34.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Shorts de Praia', 24.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Macacão Floral', 79.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Camiseta Listrada', 41.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Terno Clássico', 199.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Vestido Longo', 129.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Calça Flare', 59.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Jaqueta Jeans', 89.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Saia Lápis', 44.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Moletom Estiloso', 54.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Legging Casual', 34.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Jaqueta Corta-Vento', 79.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Shorts Jeans Desbotado', 59.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blusa de Tricô', 49.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Vestido Estampado', 119.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Calça Skinny', 69.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blazer Moderno', 89.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Macacão de Linho', 74.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Camiseta Vintage', 34.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Casaco de Lã', 129.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Saia Plissada', 49.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Shorts de Corrida', 29.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Jaqueta de Algodão', 44.25);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Bermuda de Praia', 54.90);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Macacão de Verão', 89.50);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Camiseta Estampada', 39.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Blusa de Renda', 59.75);
INSERT INTO PRODUTO (DESCRICAO, PRECO) VALUES ('Vestido Casual', 74.25);
